### ISSUE TITLE
Migration not working - Infinite loop of 'eth_getBlockByNumber' calls

### ISSUE THREAD

**Issue by Janaka-Steph** [DigixGlobal/truffle-lightwallet-provider#2]
Hello,

Versions:
- node: 8.1.4
- digix/truffle-lightwallet-provider: "^0.1.1"
- truffle: 3.4.4
- testrpc 4.0.1

When I run the truffle migration on testrpc I have an infinite loop of 'eth_getBlockByNumber' calls.

$ `npm run migrate`
=> request
 { id: 4759201918003999,
  jsonrpc: '2.0',
  params: [ '0x1', false ],
  method: 'eth_getBlockByNumber',
  targetUrl: 'http://localhost:8545/' }
<= response
 { id: 4759201918003999, jsonrpc: '2.0', result: null }
... and so on

In the truffle.js file, I load the path to a supposedly valid keystore generated by Sigmate and the password (I use dotenv to load the env variables).

```
networks: {
    development: {
      provider: new LightWalletProvider({
        keystore: KEYSTORE,
        password: PASSWORD,
        rpcUrl: 'http://localhost:8545/',
        debug: true,
        prefund: 1e18, 
        pollingInterval: 500
      }),
      network_id: '*'
    },
```

Any idea ? Thank you

**Comment by IstoraMandiri** [comment]
I'll take a look at this tomorrow. I think it's to do with prefund. Does it work without?

Thanks for the report.

**Comment by Janaka-Steph** [comment]
Hello,

No it doesn't work without prefund, nor without pollingInterval (just take longer but still have this loop). I saw that I have the same issue when I have Metamask open. But here I don't open Metamask.
You can have a look at the repo if you want: https://github.com/asseth/dao1901/blob/truffle-lightwallet-provider/protocol/truffle.js

Thanks for your help

**Comment by IstoraMandiri** [comment]
I believe this is related to https://github.com/ethereumjs/testrpc/issues/290 ? (trying to debug)

**Comment by IstoraMandiri** [comment]
I've tried debugging this for a couple of hours and still can't figure what the issue is. I can confirm that `web3-provider-engine` is using the "fixed" version of `eth-block-tracker` (i've tried with multiple different dependancy versions), but nothing seems to work. The error for me is throwing from `ethereumjs-testrpc/node_modules/web3-provider-engine`.

I would suggest not using this with testrpc for now. Unfortunately I can't spend any more time debugging until it's a blocker for digix.

**Comment by Janaka-Steph** [comment]
Ok, I will wait before using it. Thank you for your time.
